language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
# script:
# # - yarn eslint
# # - yarn test
- yarn build:report
stages:
- name: staging
  if: branch = staging
- name: production
  if: branch = master
before_deploy:
  - yarn build
deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: "$AWS_S3_PRODUCTION_BUCKET"
    skip_cleanup: true
    acl: public_read
    cache_control: max-age=31536000
    local_dir: dist
    on:
      branch: production

  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: "$AWS_S3_STAGING_BUCKET"
    skip_cleanup: true
    acl: public_read
    cache_control: max-age=31536000
    local_dir: dist
    on:
      branch: staging
